export const JOB_LISTING="JOB_LISTING"
export const JOB_LISTING_SUCCESS="JOB_LISTING_SUCCESS"
export const JOB_LISTING_FAILED="JOB_LISTING_FAILED"

export const FILTER_JOBS="FILTER_JOBS"
export const FILTER_JOBS_SUCCESS="FILTER_JOBS_SUCCESS"
export const FILTER_JOBS_FAILED="FILTER_JOBS_FAILED"